version: '3'

services:
  api:
    container_name: FastAPI
    build: ./backend
    volumes:
      - ./backend:/app
      - /mnt/e:/app/dir
    ports:
      - "8000:8000"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

  web:
    container_name: React
    build: ./frontend
    ports:
      - "5173:4173"
    depends_on:
      - api
